profiles/urls.py
from django.urls import path
from .views import *

app_name = 'profiles'

urlpatterns = [
    path('', Index, name='index'),
    path('profiles/', ProfileListView.as_view(), name='all-profiles-view'),
    path('my-invites/', invites_recieved_view, name='my-invites-view'),
    path('to-invite/', invite_profile_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invataion, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('my-invites/accept/', accept_invatation, name='accept-invite'),
    path('my-invites/reject/', reject_invatation, name='reject-invite'),
    path("setting/", settingPage, name="setting-page"),
    path('friend-request/', friend_request, name='friend_request'),


    path('sent_msg/<str:pk>', sentMessages, name="sent_msg"),
    path('reci_msg/<str:pk>', receivedMessages, name="reci_msg"),
    path('notification/', chatNotification, name="notification"),
    path('friend/<str:pk>', Detail, name='detail'),
    path('frnd_p/<str:pk>', friend_profile, name='frnd_p'),
    
]

socialnet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('profiles.urls', namespace='profiles')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profiles/models.py
from django.db import models
from .utils import get_random_code
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.db.models import Q
from django.urls import reverse

# Create your models here.

class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender) 
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        print(qs)

        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        print(accepted)

        available = [profile for profile in profiles if profile not in accepted]
        print(available)
        return available         

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles 


class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    pic = models.ImageField(default="profile1.png", upload_to="images", blank=True, null=True)
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    objects = ProfileManager()

    @property
    def picURL(self):
        try:
            url = self.pic.url
        except:
            url = ''
        return url 

    def __str__(self):
        return f"{self.user.username}"
    
    def get_absolute_url(self):
        return reverse("profiles:detail", kwargs={"pk": self.pk})

    def get_friends(self):
        return self.friends.all()
    
    def get_friends_no(self):
        return self.friends.all().count()
    
    def get_posts_no(self):
        return self.posts.all().count()
    
    def get_all_authors_posts(self):
        return self.posts.all()
    
    def get_likes_given_no(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value=='Like':
                total_liked += 1
        return total_liked

    def get_likes_received_no(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked            

    

STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)                  

class RelationshipManager(models.Manager):
    def invatations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs

class Relationship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
     
    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"     

class ChatMessage(models.Model):
    body = models.TextField()
    msg_sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="msg_sender")
    msg_receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="msg_receiver")  
    seen = models.BooleanField(default=False)    

    def __str__(self):
        return self.body      

profiles/forms.py
from django import forms
from .models import *
from django.forms import ModelForm


class ChatMessageForm(ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={"class":"forms", "rows":3, "placeholder": "Type message here"}))
    class Meta:
        model = ChatMessage
        fields = ["body",]

class userForm(ModelForm):
    class Meta:
        model = Profile
        
        fields = ['first_name', 'last_name','email', 'pic', 'country']

profiles/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from .models import *
from django.http import JsonResponse
import json
from .forms import *
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.



@login_required
def invites_recieved_view(request):
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invatations_received(profile)
    results = list(map(lambda x: x.sender, qs))
    is_empty = False
    if len(results) == 0:
        is_empty = True

    context = {'qs': results, 'is_empty': is_empty}

    return render(request, 'profiles/my_invites.html', context)

@login_required
def accept_invatation(request):
    if request.method=="POST":
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('profiles:my-invites-view')

@login_required
def reject_invatation(request):
    if request.method=="POST":
        pk = request.POST.get('profile_pk')
        receiver = Profile.objects.get(user=request.user)
        sender = Profile.objects.get(pk=pk)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('profiles:my-invites-view')


@login_required
def invite_profile_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles_to_invite(user)

    context = {'qs': qs}

    return render(request, 'profiles/to_invite_list.html', context)

@login_required
def profile_list_view(request):
    user = request.user
    qs = Profile.objects.get_all_profiles(user)

    context = {'qs': qs}

    return render(request, 'profiles/profiles_list.html', context)


@login_required(login_url='login')
def friend_profile(request,pk):
    friend = Profile.objects.get(user_id=pk)
    user = request.user.profile
    profile = Profile.objects.get (id=friend.user.id)
    context = {'friend':friend, 'user':user, 'profile':profile}
    return render(request, 'profiles/frnd_p.html', context)
    
@login_required
def Index(request):
    user = request.user
    friends = user.friends.all()
    context ={'user':user, 'friends':friends}
    return render(request, 'profiles/index.html', context)

def friend_request(request):
    return render(request, 'profiles/frnd_request.html')

@login_required(login_url='login')
def settingPage(request):
    user = request.user.profile
    form = userForm(instance=user)
    
    if request.method == 'POST':
        form = userForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
    context = {'form': form}
    return render(request, 'profiles/settings.html', context)

@login_required
def Detail(request,pk):
    friend = Profile.objects.get(user_id=pk)
    user = request.user.profile
    profile = Profile.objects.get (id=friend.user.id)
    chats = ChatMessage.objects.all()
    reci_chats = ChatMessage.objects.filter( msg_sender=profile, msg_receiver=user )
    reci_chats.update(seen=True)
    form = ChatMessageForm()
    if request.method == "POST":
        form = ChatMessageForm(request.POST)
        if form.is_valid():
            chat_message = form.save(commit=False)
            chat_message.msg_sender = user
            chat_message.msg_receiver = profile
            chat_message.save()
            return redirect("detail", pk=profile.id)

    context = {'friend':friend, 'form':form, 'user':user, 'profile':profile, 'chats':chats, 'num': reci_chats.count()}
    return render(request, 'profiles/detail.html', context)

@login_required
def sentMessages(request, pk):
    user = request.user.profile
    friend = Profile.objects.get(user_id=pk)
    profile = Profile.objects.get(id=friend.user.id)
    data = json.loads(request.body)
    new_chat = data["msg"]
    new_chat_message = ChatMessage.objects.create(body=new_chat, msg_sender=user, msg_receiver=profile, seen=False)
    print(new_chat)
    return JsonResponse(new_chat_message.body, safe=False)

@login_required
def receivedMessages(request, pk):
    user = request.user.profile
    friend = Profile.objects.get(user_id=pk)
    profile = Profile.objects.get(id=friend.user.id)
    arr = []
    chats = ChatMessage.objects.filter( msg_sender=profile, msg_receiver=user )
    for chat in chats:
        arr.append(chat.body)
    return JsonResponse(arr, safe=False)    

@login_required
def chatNotification(request):
    
   user = request.user.profile
   friends = user.friends.all()
   arr = []
   for friend in friends:
    chats = ChatMessage.objects.filter(msg_sender__id=friend.profile.id, msg_receiver=user, seen=False)
    arr.append(chats.count())

   return JsonResponse(arr, safe=False)


class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/profiles_list.html'
    # context_object_name = 'qs'
    
    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username=self.request.user)
        profile = Profile.objects.get(user=user)
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver =[]
        rel_sender = []
        for item in rel_r:
            rel_receiver.append(item.receiver.user)
        for item in rel_s:
            rel_sender.append(item.sender.user)
        context["rel_receiver"] = rel_receiver
        context["rel_sender"] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True

        return context
    
    
def send_invataion(request):
    if request.method=='POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile-view')


def remove_from_friends(request):
    if request.method=='POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender)))
        
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile-view')

profiles/templates/profiles/detail.html
{% extends "base.html" %}

{% block content %}

<style>
    .forms{
        border: 1px solid rgb(90, 205, 201);
        
        width: 100%;
        border-radius: 5px;
        padding: 10px 10px;
        font-size: 18px;
    }
</style>

<div class="chat-container2">
    <div class="identity">
        <div>
           <a href="{% url 'profiles:index' %}">
            <svg
            xmlns="http://www.w3.org/2000/svg"
            width="26"
            height="26"
            fill="currentColor"
            class="bi bi-house"
            viewBox="0 0 16 16"
          >
            <path
              fill-rule="evenodd"
              d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"
            />
            <path
              fill-rule="evenodd"
              d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"
            />
          </svg>
           </a>
        </div>

        <a href="{% url 'profiles:frnd_p' friend.user.id %}" style="color:black; text-decoration: none"><h3>{{friend}}</h3></a>

        <div class="pro-pic">
            <img src="{{friend.pic.url}}" alt="profile-picture">
        </div>


    </div>

    <div class="sub-container">


        <div class="chat-body" id="chat-body">

            
            {% for chat in chats %}
            {% if chat.msg_sender == user and chat.msg_receiver == profile %}

            <div class="chat-box-sent">
                {{chat}}
            </div>

            {% elif chat.msg_sender == profile and chat.msg_receiver == user %}

            <div class="chat-box-received">
                {{chat}}
            </div>

            {% endif %}



            

            {% endfor %}


        

            <div class="chat-box-sent" id ="chat-box-sent" style="display: none">
               
            </div>

            
        </div>
    
        <form action="" id="myform" method="POST">
            {% csrf_token %}
            
            {{form.body}}
            
            <button type = "submit" id = "submit">Send</button>
        </form>


    </div>

   



</div>

<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');


    let form = document.getElementById("myform")
    form.addEventListener("submit", sendChat)

    function sendChat(e){
        e.preventDefault()
        let chatMessage = document.getElementById("id_body").value
        console.log(chatMessage)

        const data = { msg: chatMessage };
        let url = "{% url 'profiles:sent_msg' friend.user.id %}"


fetch(url, {
    method: 'POST', // or 'PUT'
    headers: {
        'Content-Type': 'application/json',
        'X-CSRFToken': csrftoken
    },
    body: JSON.stringify(data),
})
.then((response) => response.json())
.then((data) => {
    console.log('Success:', data);
    let chat_body = document.getElementById('chat-body')
    let chatMessageBox = document.createElement("div")
    chatMessageBox.classList.add("chat-box-sent")
    chatMessageBox.innerText = data
    chat_body.append(chatMessageBox)
    document.getElementById("id_body").value=""
})
.catch((error) => {
    console.error('Error:', error);
});

}

setInterval(receivedMessage, 2000)

let counter = {{num}}

function receivedMessage(){

    let url = "{% url 'profiles:reci_msg' friend.user.id %}"

    fetch(url)
    
    .then((response) => response.json())
    .then((data) => {
    console.log('Success:', data);

    if(data.length == 0){}

    else{
        let lastMsg = data[data.length-1]
        if(counter == data.length){console.log("there is no chat")}
        
        else{
            let chat_body = document.getElementById('chat-body')
            let chatMessageBox = document.createElement("div")
            chatMessageBox.classList.add("chat-box-received")
            chatMessageBox.innerText = lastMsg
            chat_body.append(chatMessageBox)
            document.getElementById("id_body").value=""  
        }
    }

    counter = data.length
    })
    .catch((error) => {
    console.error('Error:', error);
    });    
}

function chatNotification(){

}


</script>

{% endblock %}

profiles/templates/profiles/frnd_request.html
{% extends "base.html" %}


{% block content %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}

{% url 'profiles:all-profiles-view' as path_to_all_profiles %}


<div class="chat-container">
    <a class="btn btn-warning" href="{% url 'profiles:index'%}">&#8592; Back</a>
    <hr>
    <div class="item">
       <h2>Friends request</h2>
       <br>
            <i class="dropdown icon"></i>
            <div class="menu">
                <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                    All Profiles
                </a>
                <br>
                
                <br>
                <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                    Received Request &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                </a>
            </div>
        
    </div>
</div>
{% endblock %}

profiles/templates/profiles/index.html
{% extends "base.html" %}




{% block content %}
{% if user.is_authenticated %}
<div class="chat-container">
    <div class="main">
      <div class="logo">
        ChatMe
      </div>
     
      <div class="sub-main">
        <div class="main-user">
          <img src="{{user.profile.pic.url}}" alt="profile picture" />
          
        </div>
        <p>@{{request.user.username}}</p>
       
      </div>
    </div>
   
    <div class="header">Messages</div>
  
    <div class="friends-container">
     
      {% for friend in friends %}
      
        <a href="{{friend.get_absolute_url}}" style="color:black; text-decoration: none">
          <div class="friends">
            <div class="pic">
              <img src="{{friend.pic.url}}" alt="" />
            </div>
            <div class="name">
              <h5>{{friend}}</h5>
              
            </div>
            <div class="time_new_msg">
              {% comment %} <p>7:30am</p> {% endcomment %}
            
              <div class="msg">0</div>
      
              
            </div>
          </div>
        </a>
        
  
      {% endfor %}
    </div>
  
    <div class="footer">
      <div>
        <a href="{% url 'profiles:friend_request' %}"> 
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="26"
          height="26"
          fill="currentColor"
          class="bi bi-person-plus"
          viewBox="0 0 16 16"
        >
          <path
            d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"
          />
          <path
            fill-rule="evenodd"
            d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"
          />
        </svg>
      </a>
    </div>
  
      <div>
        <a href="{% url 'profiles:index' %}">
        <svg
        
          xmlns="http://www.w3.org/2000/svg"
          width="26"
          height="26"
          fill="currentColor"
          class="bi bi-house"
          viewBox="0 0 16 16"
        >
          <path
            fill-rule="evenodd"
            d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"
          />
          <path
            fill-rule="evenodd"
            d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"
          />
        </svg>
        </a>
      </div>
  
      <div>
        <a href="{% url 'profiles:setting-page' %}">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="26"
          height="26"
          fill="currentColor"
          class="bi bi-gear"
          viewBox="0 0 16 16"
        >
          <path
            d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"
          />
          <path
            d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z"
          />
        </svg>
        </a>
      </div>
    </div>
  </div>

  <script>
      setInterval(getNotification, 1000)

    function getNotification(){
      let url = "{% url 'profiles:notification' %}"

      fetch(url)
      .then(res=>res.json())
      .then(data=>{
        console.log(data)
        let chatNotificationBtn = document.getElementsByClassName("msg")
        for(let i = 0; i<data.length; i++){
          chatNotificationBtn[i].innerText = data[i]
        }
      })
      .catch(error=> console.log(error))
    }
  </script>

{% endif %}
  
{% endblock %}

profiles/templates/profiles/my_invites.html
{% extends 'base.html' %}
{% block content %}
<div class="chat-container">
    <a class="btn btn-warning" href="{% url 'profiles:friend_request'%}">&#8592; Back</a>
   <div class="friends-container">
        {% block title %}
        my invites
        {% endblock title %}

        
        {% if is_empty %}
            <h1>No invitations...</h1>
        {% endif %}    

        {% for obj in qs %}

            <div class="ui segment">
                <div class="ui grid">
                    <div class="row">
                        <div class="three wide column">
                            <img class="ui small circular image" src="{{obj.pic.url}}">
                        </div>
                        <div class="thirteen wide column">
                            <h3>{{obj.user}}</h3>
                            <p>{{obj.bio}}</p>
                            <br>
                            <a href="{{obj.get_absolute_url}}"><button class="ui primary button w-big mb-5">See profile</button></a>
                            <form action="{% url 'profiles:accept-invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                                <button type="submit" class="ui positive basic button w-big mb-5"><i class="check icon"></i>Accept invite</button>
                            </form>
                            <form action="{% url 'profiles:reject-invite' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                                <button type="submit" class="ui negative basic button w-big mb-5"><i class="close icon"></i>Reject invite</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>  
        {% endfor %}  
   </div>
</div>  


{% endblock content %}

profiles/templates/profiles/profiles_list.html
{% extends 'base.html' %}

{% block title %}
all profiles
{% endblock title %}

{% block content %}

   
<div class="chat-container">
    <a class="btn btn-warning" href="{% url 'profiles:friend_request'%}">&#8592; Back</a>
    <div class="friends-container">
        {% if is_empty %}
       <h1>No profile</h1>
    {% endif %}
    {% for obj in object_list %}
       <div class="ui segment">
        <div class="ui grid">
            <div class="row">
                <div class="three wide column">
                    <img class="ui small circular image" src="{{obj.avatar.url}}">
                </div>
                <div class="thirteen wide column">
                    <h3>{{obj.user}}</h3>
                    <P>{{obj.bio}}</P>
                    <a href="{{obj.get_absolute_url}}"><button class="ui primary button mb-5 w-big">See profile</button></a>
                    <br>
                     
                    {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                        <form action="{% url 'profiles:send-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                            <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Add to friends</button>
                        </form>
                    {% endif %}
                    {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
                        <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>waitin for approval</button>
                    {% endif %}
                    
                    {% if request.user in obj.friends.all %}
                        <form action="{% url 'profiles:remove-friend' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                            
                            <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                        
                        </form>
                    {% endif %}
            </div>
            </div>
        </div>
       </div>
    {% endfor %}
    </div>
</div>
{% endblock content%}

profiles/templates/profiles/to_invite_list.html
{% extends 'base.html' %}

{% block title %}
invite friends
{% endblock title %}

{% block content %}
<ul>
{% for item in qs %}
    <li>{{item}}</li>
{% endfor %}    
</ul>

{% endblock content%}